Fixes
crypto-pepe/firewall-executor pull request #17
Opened 2022-06-06 11:32 UTC by horny-manul

Closes #8 
Closes #9
Closes #10 
Closes #11

2022-06-06 11:49 UTC, citizensix commented on src/api/server.rs
> +                        code: 400,
```use StatusCode::...```

2022-06-06 11:50 UTC, citizensix commented on src/api/routes/ban.rs
> +                        code: 400,
StatusCode::BAD_REQUEST.as_u16()

2022-06-06 11:53 UTC, citizensix commented on src/api/routes/ban.rs
> +                "" => {
`s.is_empty`

2022-06-06 11:56 UTC, citizensix commented on src/api/routes/ban.rs
>          Some(s) => match s.to_str() {
You can use `map_or()` in this case

2022-06-06 11:57 UTC, citizensix reviewed
.

2022-06-06 16:56 UTC, stuffy-idler requested changes

2022-06-06 17:01 UTC, stuffy-idler commented
@dummy-duck please check whether issues were resolved

2022-06-07 15:47 UTC, stuffy-idler requested changes

2022-06-07 16:33 UTC, dummy-duck requested changes
1) Wrong Dockerfile - image can't be builded
2) https://github.com/crypto-pepe/firewall-executor/issues/10 - not solved
3) https://github.com/crypto-pepe/firewall-executor/issues/9 - not solved

2022-06-10 08:17 UTC, horny-manul commented
@dummy-duck 

> https://github.com/crypto-pepe/firewall-executor/issues/10 - not solved

In your example request ttl is 4294967297, which is not uint32 therefore it fails. 

> https://github.com/crypto-pepe/firewall-executor/issues/9 - not solved

Fixed. Now all unknown fields produces an error

2022-06-10 08:40 UTC, stuffy-idler commented
@horny-manul
> In your example request ttl is 4294967297, which is not uint32 therefore it fails.

Will server response with bad request for this case? It has to

2022-06-10 08:44 UTC, stuffy-idler requested changes

2022-06-10 08:44 UTC, stuffy-idler commented on src/api/http_error.rs
>          f.write_str(serde_json::to_string(self).unwrap().as_str())
Has not to panic. 
Let's get rid of `unwrap`, change it to `Err`

2022-06-10 08:44 UTC, stuffy-idler commented on src/api/routes/ban.rs
>  pub struct BanRequest {
`Display` impl has not to panic (`expect` usage). Please fix it – impl is fallible, therefore it can be changed to `Err`

2022-06-10 09:00 UTC, stuffy-idler approved these changes

2022-06-10 09:25 UTC, merged